# Generated by Django 5.0.1 on 2024-02-12 12:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality')])),
                ('definition', models.TextField()),
                ('solution', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_kind', models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality')])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_saved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problems_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.file')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template')),
            ],
            options={
                'unique_together': {('author', 'name')},
            },
        ),
    ]
