# Generated by Django 5.0.4 on 2024-05-05 22:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_saved', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('answer_key_pdf', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('pdf', models.FileField(upload_to='')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality')])),
                ('definition', models.TextField()),
                ('solution', models.TextField()),
                ('test_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_kind', models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality')], default=1)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template')),
            ],
            options={
                'unique_together': {('template', 'problem_kind')},
            },
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(('is_saved', False), ('name__isnull', False), _connector='OR'), name='saved_test_has_name'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('author', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='testversion',
            unique_together={('test', 'version_number')},
        ),
    ]
