# Generated by Django 4.2.16 on 2025-04-13 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Only you can see this name', max_length=255, verbose_name='Name')),
                ('title', models.TextField(blank=True, help_text='Anything you add to this field will be rendered at the top of the test document', verbose_name='Title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('is_saved', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('answer_key_pdf', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField(default=1)),
                ('pdf', models.FileField(upload_to='')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestVersionProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(default='', help_text='The topic of the problem (e.g., ARVUHULGAD, AVALDISED, etc.)', max_length=100)),
                ('difficulty', models.CharField(choices=[('A', 'Lihtne'), ('B', 'Keskmine'), ('C', 'Raske')], default='A', help_text='The difficulty of the problem', max_length=1)),
                ('definition', models.TextField()),
                ('solution', models.TextField()),
                ('test_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(default='ARVUHULGAD', max_length=100)),
                ('difficulty', models.CharField(choices=[('A', 'Easy'), ('B', 'Medium'), ('C', 'Hard')], default='A', max_length=1)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template')),
            ],
        ),
        migrations.AddConstraint(
            model_name='testversion',
            constraint=models.UniqueConstraint(fields=('test', 'version_number'), name='test_does_not_have_any_testversion_number_more_than_once'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='test_name_is_unique_per_author'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(('is_saved', False), ('name__isnull', False), _connector='OR'), name='saved_test_has_name'),
        ),
        migrations.AddConstraint(
            model_name='templateproblem',
            constraint=models.UniqueConstraint(fields=('template', 'topic', 'difficulty'), name='unique_topic_difficulty_per_template'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='template_name_is_unique_per_author'),
        ),
    ]
