# Generated by Django 5.0.1 on 2024-02-12 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pset',
            name='problem_count',
            field=models.IntegerField(default=69, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
