# Generated by Django 5.0.2 on 2024-03-02 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test',
            name='saved_test_has_name',
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(('is_saved', False), ('name__isnull', False), _connector='OR'), name='saved_test_has_name'),
        ),
    ]
