# Generated by Django 5.0.2 on 2024-04-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='header',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
