# Generated by Django 4.2.16 on 2025-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testversionproblem',
            name='topic',
            field=models.CharField(default='AVALDISED', help_text='The topic of the problem (e.g., ARVUHULGAD, AVALDISED, etc.)', max_length=100),
        ),
    ]
