# Generated by Django 5.0.4 on 2024-05-09 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problem_created_at_problem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name'),
        ),
    ]
