# Generated by Django 4.2.16 on 2025-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_testversionproblem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='testversionproblem',
            name='spec',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
