# Generated by Django 5.0.2 on 2024-03-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_test_saved_test_has_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='template',
        ),
        migrations.AlterField(
            model_name='testversion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
    ]
