# Generated by Django 5.0.2 on 2024-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_template_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='header',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
