# Generated by Django 5.0.4 on 2024-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_template_name_alter_template_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Only you can see this name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, help_text='Anything you add to this field will be rendered at the top of the test document', max_length=1000, verbose_name='Title'),
        ),
    ]
