# Generated by Django 4.2.16 on 2025-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testversionproblem_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproblem',
            name='topic',
            field=models.CharField(default='AVALDISED', max_length=100),
        ),
    ]
