# Generated by Django 5.0.2 on 2024-04-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='header',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='header',
            new_name='title',
        ),
    ]
