# Generated by Django 5.0.4 on 2024-08-13 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_template_name_alter_template_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='templateproblem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testversion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='template_name_is_unique_per_author'),
        ),
        migrations.AddConstraint(
            model_name='templateproblem',
            constraint=models.UniqueConstraint(fields=('template', 'problem_kind'), name='problemkind_only_appears_once_per_template'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='test_name_is_unique_per_author'),
        ),
        migrations.AddConstraint(
            model_name='testversion',
            constraint=models.UniqueConstraint(fields=('test', 'version_number'), name='test_does_not_have_any_testversion_number_more_than_once'),
        ),
    ]
