# Generated by Django 5.0.4 on 2024-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_header_template_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality')]),
        ),
        migrations.AlterField(
            model_name='templateproblem',
            name='problem_kind',
            field=models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality')], default=1),
        ),
    ]
