# Generated by Django 4.2.16 on 2025-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_templateproblem_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproblem',
            name='topic',
            field=models.CharField(choices=[('NUMBER_SETS', 'Number sets'), ('EXPRESSIONS', 'Expressions'), ('EXPONENTIAL_LOG', 'Exponential and logarithmic functions'), ('FUNCTIONS_SEQUENCES', 'Functions and sequences'), ('TRIGONOMETRY', 'Trigonometry I and II'), ('EQUATIONS', 'Equations and systems of equations'), ('INEQUALITIES', 'Inequalities and systems of inequalities'), ('VECTORS', 'Vectors in the plane and line equations'), ('TRIG_LIMITS', 'Trigonometric functions, limits and results'), ('DERIVATIVE_APPS', 'Applications of the derivative'), ('INTEGRAL', 'Integral and plane geometry'), ('LINE_PLANE_SPACE', 'Line and plane in space'), ('SOLID_GEOMETRY', 'Solid geometry'), ('APPLICATIONS', 'Applications of mathematics, study of real-world processes')], max_length=100),
        ),
    ]
