# Generated by Django 5.0.4 on 2024-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_template_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality'), (4, 'Exponent reduction problem'), (5, 'Exponent operation problem')]),
        ),
        migrations.AlterField(
            model_name='templateproblem',
            name='problem_kind',
            field=models.IntegerField(choices=[(1, 'Linear inequality'), (2, 'Quadratic inequality'), (3, 'Fractional inequality'), (4, 'Exponent reduction problem'), (5, 'Exponent operation problem')], default=1),
        ),
    ]
