# Generated by Django 4.2.16 on 2025-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_templateproblem_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproblem',
            name='topic',
            field=models.CharField(choices=[('ARVUHULGAD', 'Arvuhulgad'), ('AVALDISED', 'Avaldised'), ('EKSPONENT_JA_LOG', 'Eksponent- ja logaritmfunktsioon'), ('FUNKTSIOONID_JA_ARVJADAD', 'Funktsioonid ja arvjadad'), ('TRIGONOMEETRIA_I_II', 'Trigonomeetrilised I ja II'), ('VÕRRANDID', 'Võrrandid ja võrrandisüsteemid'), ('VÕRRATUS', 'Võrratused ja võrratusesüsteemid'), ('VEKTOR_JA_JOONEVÕRRAND', 'Vektor tasandil ja joone võrrand'), ('TRIG_FUN_PIIR_TULEM', 'Trigonomeetrilised funktsioonid, piirväärtus ja tulemised'), ('TULETISE_RAK', 'Tuletise rakendused'), ('INTEGRAAL_JA_PLANIMEETRIA', 'Integraal ja planimeetria'), ('SIRGE_TASAND_RUUMIS', 'Sirge ja tasand ruumis'), ('STEREOMEETRIA', 'Stereomeetria'), ('MAT_RAKENDUSED', 'Matemaatika rakendused, reaalse protsessi uurimine')], max_length=100),
        ),
    ]
