# Generated by Django 5.0.4 on 2024-08-23 18:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_problem_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRenderingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solving_area_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Problem',
            new_name='TestVersionProblem',
        ),
    ]
