# Generated by Django 4.2.21 on 2025-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_templateproblem_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproblem',
            name='topic',
            field=models.CharField(choices=[('AVALDISED', 'Avaldised'), ('EKSPONENT/LOGARITM VÕRRANDID JA VÕRRATUSED', 'Eksponent/logaritm võrrandid ja võrratused'), ('EKSPONENTFUNKTSIOON', 'Eksponentfunktsioon'), ('LOGARITMI_DEFINITSIOON', 'Logaritmi definitsioon'), ('MATEMAATIKA RAKENDUSED', 'Matemaatika rakendused'), ('TRIGONOMEETRIA_II', 'Trigonometria II'), ('TRIGONOMEETRILISED_AVALDISED', 'Trigonometrilised avaldised'), ('VÕRRANDID_JA_VÕRRANDISÜSTEEMID', 'Võrrandid ja võrrandisüsteemid')], max_length=100),
        ),
    ]
