# Generated by Django 5.0.4 on 2024-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_problemrenderingsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.TextField(blank=True, help_text='Anything you add to this field will be rendered at the top of the test document', verbose_name='Title'),
        ),
    ]
