# Generated by Django 5.0.4 on 2024-09-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_template_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemRenderingSettings',
        ),
    ]
