from typing import Any

from sympy.core.relational import Relational
from sympy.sets.sets import Set

class Expr: ...

class Symbol:
    def __init__(self, name: str, **assumptions: Any): ...

def __getattr__(name: str) -> Any: ...
def sympify(
    a, locals=None, convert_xor=True, strict=False, rational=False, evaluate=None
) -> Any: ...
def solveset(f: Expr | Relational, symbol: Symbol | str, domain: Set) -> Set: ...
